In [7]:
import pandas as pd
crime_df = pd.read_csv("Data Files/crime_dataset_india.csv")
print(crime_df.columns)
crime_count = crime_df['City'].value_counts().reset_index()
crime_count

Index(['Report Number', 'Date Reported', 'Date of Occurrence',
       'Time of Occurrence', 'City', 'Crime Code', 'Crime Description',
       'Victim Age', 'Victim Gender', 'Weapon Used', 'Crime Domain',
       'Police Deployed', 'Case Closed', 'Date Case Closed'],
      dtype='object')

             City  count
0           Delhi   5400
1          Mumbai   4415
2       Bangalore   3588
3       Hyderabad   2881
4         Kolkata   2518
5         Chennai   2493
6            Pune   2212
7       Ahmedabad   1817
8          Jaipur   1479
9         Lucknow   1456
10         Kanpur   1112
11          Surat   1111
12         Nagpur   1053
13           Agra    764
14       Ludhiana    761
15  Visakhapatnam    728
16          Thane    706
17      Ghaziabad    704
18         Indore    699
19          Patna    695
20         Bhopal    690
21         Meerut    395
22       Srinagar    371
23         Nashik    366
24          Vasai    362
25       Varanasi    355
26         Kalyan    355
27      Faridabad    354
28         Rajkot    320

In [3]:
crime_type_count = crime_df["Crime Description"].value_counts().reset_index()
crime_type_count

      Crime Description  count
0              BURGLARY   1980
1             VANDALISM   1975
2                 FRAUD   1965
3     DOMESTIC VIOLENCE   1932
4       FIREARM OFFENSE   1931
5               ROBBERY   1928
6            KIDNAPPING   1920
7        IDENTITY THEFT   1918
8        SEXUAL ASSAULT   1917
9               ASSAULT   1915
10    TRAFFIC VIOLATION   1915
11  PUBLIC INTOXICATION   1912
12             HOMICIDE   1909
13           CYBERCRIME   1899
14   ILLEGAL POSSESSION   1895
15                ARSON   1894
16         DRUG OFFENSE   1890
17            EXTORTION   1873
18       COUNTERFEITING   1871
19     VEHICLE - STOLEN   1862
20          SHOPLIFTING   1859